dpis: [75, 150, 300]

scales:
    - 25000
    - 50000
    - 100000
    - 200000
    - 500000
    - 1000000
    - 2000000
    - 4000000

hosts:
    - !localMatch
        dummy: true
    - !ipMatch
        ip: 0.0.0.0
        mask: 0.0.0.0

layouts:
    Legal:
        metaData:
            title: "${mapTitle}"
            author: "GeoExplorer"
            subject: "Simple layout"
            keywords: "map,print"
            creator: "GeoExplorer"

        mainPage:
            pageSize: LEGAL
            items:
                - !text
                    text: "${mapTitle}"
                    fontSize: 30
                    spacingAfter: 30
                - !map
                    spacingAfter: 30
                    width: 440
                    height: 483
                - !columns
                    absoluteX: 410
                    absoluteY: 210
                    width: 100
                    items:
                        - !scalebar
                            type: bar
                            maxSize: 100
                            barBgColor: white
                            fontSize: 8
                            align: right
                - !text
                    text: "${comment}"
                    spacingAfter: 30

    A4 portrait:
        metaData:
            title: "${mapTitle}"
            author: "GeoExplorer"
            subject: "Simple layout"
            keywords: "map,print"
            creator: "GeoExplorer"

        mainPage:
            pageSize: A4
            rotation: true
            items:
                - !text
                    text: "${mapTitle}"
                    fontSize: 30
                    spacingAfter: 30
                - !map
                    spacingAfter: 30
                    width: 440
                    height: 600
                - !columns
                    absoluteX: 410
                    absoluteY: 210
                    width: 100
                    items:
                        - !scalebar
                            type: bar
                            maxSize: 100
                            barBgColor: white
                            fontSize: 8
                            align: right
                - !text
                    text: "${comment}"
                    spacingAfter: 30
